# Terraform init, plan

steps:
- name: 'gcr.io/agmsb-k8s-ops/terraform'
  args: ['init',
    '-backend-config=project=agmsb-k8s-ops',
    '-backend-config=bucket=agmsb-terraform-state']
  env:
    - "TF_VAR_project-name=agmsb-k8s-ops"

- name: 'gcr.io/agmsb-k8s-ops/terraform'
  args: ['plan']
  env:
    - "TF_VAR_project-name=agmsb-k8s-ops"