# Terraform init, plan, apply 

steps:
- name: 'gcr.io/agmsb-tech-ops/terraform'
  args: ['init',
    '-backend-config=project=agmsb-tech-ops',
    '-backend-config=bucket=agmsb-tech-ops-tfstate']
  env:
    - "TF_VAR_project-name=agmsb-tech-ops"

- name: 'gcr.io/agmsb-tech-ops/terraform'
  args: ['plan']
  env:
    - "TF_VAR_project-name=agmsb-tech-ops"

 - name: 'gcr.io/agmsb-tech-ops/terraform'
  args: ['apply', '-auto-approve']
  env:
    - "TF_VAR_project-name=agmsb-tech-ops"
